config/routes.rb
Rails.application.routes.draw do
  namespace :have_less do
    resources :drinks
  end

  root 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  # def initialize(user)
  #   #abort("Message goes here")
  #   user ||= User.new # guest user
  #   #abort('some user')
  #   if user.role == 'admin'
  #     can :manage, :all
  #   elsif user.role == 'user'
  #     can :manage, Micropost do |micropost|
  #       micropost.try(:owner) == user
  #     end
  #     can :update, User do |users|
  #       users.try(:owner) == user
  #     end
  #   else
  #     can :read, :all
  #   end
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/have_less/drink.rb
class Drink < ApplicationRecord
  has_many :drink_sizes

  validates_presence_of :name

  enum drink_type: %w[coffee milk_tea alcohol other]

  attr_accessor :name, :drink_type

  scope :coffee, -> { where(drink_type: :coffee) }
  scope :milk_tea, -> { where(drink_type: :milk_tea) }
  scope :alcohol, -> { where(drink_type: :alcohol) }
  scope :other, -> { where(drink_type: :other) }
end

app/models/have_less/drink_size.rb
class DrinkSize < ApplicationRecord
  belongs_to :drink, dependent: :destroy

  enum sizes: %w[small medium large extra_large]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/have_less/drink_sizes_controller.rb
class HaveLess::DrinkSizesController < ApplicationController
  def index; end
end

app/controllers/have_less/drinks_controller.rb
module HaveLess
  class DrinksController < ApplicationController
    def index
      @drinks = Drink.all
    end

    def new
      @drink = Drink.new
    end

    def create
      @drink = Drink.new(drink_params)

      if @drink.save
        redirect_to have_less_drinks_path, notice: 'Drink created.'
      else
        render action: 'new'
      end
    end

    def edit; end

    def show
      @drink = Drink.find(params[:id])
    end

    private

    def drink_params
      params.require(:drink).permit(:name, :drink_type)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/have_less/drinks/index.haml
%h1
  Drinks

.button
  = link_to 'Create Drink', new_have_less_drink_path

.table.drinks-list
  %table
    - if @drinks.any?
      %thead
        %tr
          %td Name
          %td Type
          %td Created at
      %tbody
        - @drinks.each do |drink|
          %tr
            %td= drink.name.humanize
            %td= drink.drink_type&.humanize
            %td= drink.created_at
            %td= link_to 'Show', have_less_drink_path(drink)
            %td= link_to 'Edit', edit_have_less_drink_path(drink)
    - else
      %tbody
        There are currently no drinks here. Add some!

app/views/have_less/drinks/new.haml
%h1 Create Drink
.form
  = form_for [:have_less, @drink] do |f|
    = f.text_field :name
    = f.label 'Drink Type'
    - drink_type_options = Drink.drink_types.map { |key, value| [key.to_s.humanize, key] }
    = f.select :drink_type, options_for_select(drink_type_options), prompt: 'Select drink type...'
    = f.submit 'Create Drink', class: 'button'
  = link_to 'Back', have_less_drinks_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Piggy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.haml
.Welcome
  %header
    Welcome to Piggy!
  %p
    A money-saving app.

  %h2
    Have less of
  .button
    = link_to 'Drinks', have_less_drinks_path